#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
server:
  port: 9095
spring:
  sql:
    init:
      mode: always
      platform: h2
  datasource:
    username: sa
    password: root
    url: jdbc:h2:mem:rbac-spring-boot-test
    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
  #JPA Hibernate
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

